"""Windows input surface for short SRV steering pulses.

This module is the only steering subsystem component that injects input. It uses
Win32 SendInput with scan codes to press and release configured steering keys,
while a low-level keyboard hook observes physical player keys so manual control
can abort assistance. It does not decide when to steer and does not control
throttle except for the explicit three-second arrival brake requested by the UI.

Safety contract: commands require game focus, configured plain steering keys, a
short bounded duration, and a watchdog release path independent of the Qt timer.
Injected keys are distinguished from physical keys and the hook never blocks the
player's input stream.

Refusals/aborts are intentional: missing bindings, held keys, focus loss,
unobservable modifiers/axes, reserved F8 conflicts, joystick polling failure,
SendInput errors, expired direction-test authorization, and manual steering all
prevent or stop injected steering so player control remains authoritative.
"""
import ctypes as C
from ctypes import wintypes as W
import threading
import time
import xml.etree.ElementTree as ET
from radar_input import virtual_key, JoyCaps, JoyInfo
from i18n import translate


class KeyInput(C.Structure):
    """Keyboard portion of the Win32 INPUT structure used by SendInput.

    The structure is plain ctypes data with no lifecycle of its own. Fields are
    populated immediately before a single SendInput call and are not shared
    across threads.
    """

    _fields_ = [('vk', W.WORD), ('scan', W.WORD), ('flags', W.DWORD),
                ('time', W.DWORD), ('extra', C.c_size_t)]


class MouseInput(C.Structure):
    """Mouse portion of the Win32 INPUT union, kept for ABI layout.

    Steering assistance does not send mouse events, but the union must match the
    native INPUT shape. Instances are transient ctypes values.
    """

    _fields_ = [('x', W.LONG), ('y', W.LONG), ('data', W.DWORD),
                ('flags', W.DWORD), ('time', W.DWORD), ('extra', C.c_size_t)]


class InputUnion(C.Union):
    """ctypes union matching the native INPUT payload layout.

    The keyboard member is used for steering keys; the mouse member preserves
    the Windows ABI. The object owns no external resources.
    """

    _fields_ = [('keyboard', KeyInput), ('mouse', MouseInput)]


class Input(C.Structure):
    """ctypes representation of a single Win32 INPUT record.

    Instances are passed to SendInput one at a time and are not retained by the
    operating system after the call returns.
    """

    _fields_ = [('type', W.DWORD), ('value', InputUnion)]


class HookData(C.Structure):
    """Low-level keyboard hook event data provided by Windows.

    The flags field contains LLKHF_INJECTED (0x10), which lets the hook ignore
    keys generated by this module and react only to physical player input.
    """

    _fields_ = [('vk', W.DWORD), ('scan', W.DWORD), ('flags', W.DWORD),
                ('time', W.DWORD), ('extra', C.c_size_t)]


class SteeringInput:
    """Own Win32 steering injection, keyboard observation, and release watchdog.

    The instance owns configured key bindings, monitored physical keys, optional
    joystick-axis observation for manual override, hook state, a lock protecting
    held-key state, and two daemon threads. The hook thread runs the
    WH_KEYBOARD_LL message pump; the watchdog thread releases held keys every
    5 ms independently of Qt. close() ends both threads.
    """

    def __init__(self, radar):
        """Create the Windows input bridge for a passive RadarInput instance.

        Parameters:
            radar: RadarInput-like object providing binding path, focus checks,
                joystick APIs, and virtual-key observation.

        Returns:
            None.

        Side effects:
            On Windows with available radar input, loads user32 prototypes,
            installs a low-level keyboard hook, and starts daemon threads.

        Raises:
            OSError: Propagated by ctypes if required Windows DLLs cannot load.
        """
        self.radar = radar
        self.keys = {}
        self.monitored = set()
        self.physical = set()
        self.manual_pressed = False
        self.axis = None
        self.message = translate('SteeringInput', 'Steering is not configured')
        self.held = None
        self.deadline = 0
        self.window = None
        self.hook = None
        self.lock = threading.RLock()
        self.done = threading.Event()
        self.thread = None
        self.hook_thread = None
        self.hook_ready = threading.Event()
        self.error = ''
        self.sent_pulses = 0
        if not radar.available:
            return
        self.user = C.WinDLL('user32', use_last_error=True)
        self.user.SendInput.argtypes = [W.UINT, C.POINTER(Input), C.c_int]
        self.user.SendInput.restype = W.UINT
        self.user.MapVirtualKeyW.argtypes = [W.UINT, W.UINT]
        self.user.MapVirtualKeyW.restype = W.UINT
        self.user.GetForegroundWindow.restype = W.HWND
        self.user.SetWindowsHookExW.argtypes = [C.c_int, C.c_void_p, W.HINSTANCE, W.DWORD]
        self.user.SetWindowsHookExW.restype = W.HHOOK
        self.user.CallNextHookEx.argtypes = [W.HHOOK, C.c_int, W.WPARAM, W.LPARAM]
        self.user.CallNextHookEx.restype = C.c_ssize_t
        self.user.UnhookWindowsHookEx.argtypes = [W.HHOOK]
        self.user.PeekMessageW.argtypes = [C.POINTER(W.MSG),W.HWND,W.UINT,W.UINT,W.UINT]
        self.user.TranslateMessage.argtypes = [C.POINTER(W.MSG)]
        self.user.DispatchMessageW.argtypes = [C.POINTER(W.MSG)]
        self.user.DispatchMessageW.restype = C.c_ssize_t
        callback = C.WINFUNCTYPE(C.c_ssize_t, C.c_int, W.WPARAM, W.LPARAM)
        self.callback = callback(self.on_key)
        # The WH_KEYBOARD_LL (13) hook has its own message pump so player input
        # observation and held-key release do not depend on Qt callbacks.
        self.hook_thread = threading.Thread(target=self.watch_keyboard,daemon=True)
        self.hook_thread.start()
        self.hook_ready.wait(1)
        if not self.hook:
            self.message = translate('SteeringInput', 'Steering observation is unavailable on Windows')
            return
        self.thread = threading.Thread(target=self.watch_release, daemon=True)
        self.thread.start()

    def watch_keyboard(self):
        """Run the low-level keyboard hook message pump on its own thread.

        Parameters:
            None.

        Returns:
            None.

        Side effects:
            Installs WH_KEYBOARD_LL (13), dispatches queued Windows messages,
            signals hook readiness, and unhooks during shutdown.

        Raises:
            No exceptions are raised directly.
        """
        self.hook = self.user.SetWindowsHookExW(13,self.callback,None,0)
        self.hook_ready.set()
        message = W.MSG()
        try:
            while self.hook and not self.done.wait(.005):
                while self.user.PeekMessageW(C.byref(message),None,0,0,1):
                    self.user.TranslateMessage(C.byref(message))
                    self.user.DispatchMessageW(C.byref(message))
        finally:
            if self.hook:
                self.user.UnhookWindowsHookEx(self.hook)
                self.hook = None

    def on_key(self, code, message, pointer):
        """Record relevant physical steering keys and always pass events onward.

        Parameters:
            code: Hook status code from Windows; negative values are forwarded.
            message: Keyboard message such as key-down or key-up.
            pointer: Pointer to a HookData structure supplied by the hook.

        Returns:
            The result of CallNextHookEx so the player input stream continues.

        Side effects:
            Updates physical-key and manual-pressed state for monitored keys.
            LLKHF_INJECTED (0x10) events are ignored because they came from
            SendInput rather than the player's hardware.

        Raises:
            No exceptions are raised directly.
        """
        if code >= 0:
            data = C.cast(pointer, C.POINTER(HookData)).contents
            if not data.flags & 0x10 and data.vk in self.monitored:
                if message in (0x100, 0x104):
                    self.physical.add(data.vk)
                    self.manual_pressed = True
                elif message in (0x101, 0x105):
                    self.physical.discard(data.vk)
        return self.user.CallNextHookEx(self.hook, code, message, pointer)

    def load(self):
        """Load observable steering keys and optional physical steering axis.

        Parameters:
            None.

        Returns:
            None.

        Side effects:
            Releases any held key, parses the selected bindings file, updates
            monitored keys/axis/message fields, and refuses unobservable or
            unsafe configurations.

        Raises:
            No exceptions escape; OSError, ValueError, and ET.ParseError are
            converted into a user-visible message.
        """
        self.release()
        self.keys = {}
        self.axis = None
        self.monitored = set()  # Only steering keys count as manual intervention.
        self.physical.clear()
        self.manual_pressed = False
        self.sent_pulses = 0
        try:
            if not self.hook or not self.radar.path:
                raise ValueError(translate('SteeringInput', 'Steering observation or profile unavailable'))
            root = ET.parse(self.radar.path).getroot()
            keys = {}
            for direction, tag in ((-1, 'SteerLeftButton'), (1, 'SteerRightButton')):
                action = root.find(tag)
                if action is None:
                    raise ValueError(translate('SteeringInput', 'Missing {tag} in profile').format(tag=tag))
                for item in action:
                    if item.get('Device') in (None, '{NoDevice}'):
                        continue
                    vk = virtual_key(item.get('Device'), item.get('Key', ''))
                    if item.get('Device') != 'Keyboard' or vk is None or item.find('Modifier') is not None:
                        raise ValueError(translate('SteeringInput', 'Button steering requires plain keys without modifiers'))
                    self.monitored.add(vk)
                    keys.setdefault(direction, vk)
            if len(keys)!=2 or keys[-1]==keys[1]:
                raise ValueError(translate('SteeringInput', 'Bind F6 to steer left and F7 to steer right in the SRV controls'))
            if 0x77 in keys.values():
                raise ValueError(translate('SteeringInput', 'F8 is reserved to toggle assistance'))
            for item in root.iter():
                if item.get('Device') == 'Keyboard' and item.get('Key') == 'Key_F8':
                    raise ValueError(translate('SteeringInput', 'F8 is already bound in the game; unbind F8 before using assistance'))
            mouse = root.find('MouseBuggySteeringXMode')
            if mouse is not None and mouse.get('Value') not in (None, '', '0'):
                raise ValueError(translate('SteeringInput', 'Mouse steering is not yet supported by assistance'))
            binding = root.find('SteeringAxis/Binding')
            if binding is not None and binding.get('Device') not in (None, '{NoDevice}'):
                index = self.radar.joystick_id(binding.get('Device'))
                # TWCS USB identity; some drivers report only a generic name.
                if index is None and binding.get('Device') == 'T16000MTHROTTLE':
                    matches = []
                    for i in range(min(16, self.radar.winmm.joyGetNumDevs())):
                        caps = JoyCaps()
                        if self.radar.winmm.joyGetDevCapsW(i,C.byref(caps),C.sizeof(caps))==0 and (caps.mid,caps.pid)==(0x044f,0xb687):
                            matches.append(i)
                    index = matches[0] if len(matches)==1 else None
                # WinMM calls the rudder axis R (RZ), not X rotation. U/V can
                # be sliders or rotations depending on the device, so do not
                # infer those associations in this first implementation.
                axis = {'Joy_XAxis':'x','Joy_YAxis':'y','Joy_ZAxis':'z',
                        'Joy_RZAxis':'r'}.get(binding.get('Key'))
                if index is None or axis is None:
                    raise ValueError(translate('SteeringInput', 'Unable to observe the steering axis; assistance unavailable'))
                caps = JoyCaps()
                if self.radar.winmm.joyGetDevCapsW(index,C.byref(caps),C.sizeof(caps)):
                    raise ValueError(translate('SteeringInput', 'Unable to read steering axis limits'))
                low, high = getattr(caps,axis+'min'), getattr(caps,axis+'max')
                if high<=low:
                    raise ValueError(translate('SteeringInput', 'Invalid steering limits'))
                self.axis = (index, axis, low, high)
            self.keys = keys
            self.physical = {vk for vk in self.monitored if self.radar.user.GetAsyncKeyState(vk)&0x8000}
            self.message = translate('SteeringInput', 'F8: toggle · manual steering: off')
            self.error = ''
        except (OSError, ValueError, ET.ParseError) as exc:
            self.message = str(exc)

    def manual(self):
        """Report whether the player is physically steering or observation failed.

        Parameters:
            None.

        Returns:
            True for physical keyboard/axis steering, False when no manual
            steering is observed, or None when joystick polling fails.

        Side effects:
            Consumes the one-shot manual_pressed flag and polls the joystick
            axis with JOY_RETURNALL (0x00ff) through WinMM.

        Raises:
            No exceptions are raised directly.
        """
        pressed, self.manual_pressed = self.manual_pressed, False
        if pressed or self.physical:
            return True
        if self.axis:
            index, axis, low, high = self.axis
            info = JoyInfo()
            info.size, info.flags = C.sizeof(info), 0xff
            if self.radar.winmm.joyGetPosEx(index, C.byref(info)):
                return None
            value = (getattr(info,axis)-(low+high)/2)/((high-low)/2)
            return abs(value)>.05
        return False

    def send(self, vk, up=False):
        """Send one scan-code key press or release through Win32 SendInput.

        Parameters:
            vk: Virtual-key code to translate with MapVirtualKeyW.
            up: True to send KEYEVENTF_KEYUP; False to press the key.

        Returns:
            None.

        Side effects:
            Calls MapVirtualKeyW with MAPVK_VK_TO_VSC (0) and SendInput with
            KEYEVENTF_SCANCODE (0x8), KEYEVENTF_KEYUP (0x2) when releasing,
            and KEYEVENTF_EXTENDEDKEY (0x1) for extended navigation keys.

        Raises:
            OSError: If the virtual key has no scan code or SendInput does not
            report exactly one accepted INPUT record.
        """
        scan = self.user.MapVirtualKeyW(vk, 0)
        if not scan:
            raise OSError(translate('SteeringInput', 'Steering key has no scan code'))
        # SendInput must receive scan-code events; extended keys need the
        # native extended-key flag so Windows interprets their scan codes.
        flags = 0x8 | (0x2 if up else 0) | (0x1 if vk in (33,34,35,36,37,38,39,40,45,46) else 0)
        item = Input(type=1, value=InputUnion(keyboard=KeyInput(0,scan,flags,0,0)))
        # A successful single-key command must report exactly one insertion.
        if self.user.SendInput(1,C.byref(item),C.sizeof(item))!=1:
            raise OSError(translate('SteeringInput', 'Windows rejected the steering command'))

    def pulse(self, direction, duration):
        """Press one configured steering key for a bounded duration.

        Parameters:
            direction: -1 for left or +1 for right, matching loaded bindings.
            duration: Requested hold time in seconds before clamping.

        Returns:
            True when the key-down event was accepted; False when refused or an
            injection error occurred.

        Side effects:
            Refuses if a key is already held, keys are missing, or the game is
            not focused. Captures the foreground window, clamps duration to
            0.01-3.0 s, sends key-down, and lets the watchdog release it.

        Raises:
            No exceptions escape; OSError is stored in ``error`` and returns
            False after attempting release.
        """
        with self.lock:
            if self.held is not None or not self.keys or not self.radar.game_focused():
                return False
            vk = self.keys[direction]
            self.window = self.user.GetForegroundWindow()
            self.held = vk
            self.deadline = time.monotonic()+min(3.0,max(.01,duration))
            try:
                self.send(vk)
                self.sent_pulses += 1
                return True
            except OSError as exc:
                self.error = str(exc)
                self.release()
                return False

    def brake(self):
        """Hold ``S`` for the explicit three-second arrival-brake action.

        Parameters:
            None.

        Returns:
            True when the brake key-down event was accepted; otherwise False.

        Side effects:
            Releases any held steering key, refuses without game focus, holds
            virtual key 0x53 for 3.0 s, and stores injection errors in ``error``.

        Raises:
            No exceptions escape; OSError is converted to False.
        """
        with self.lock:
            self.release()
            if self.held is not None or not self.radar.game_focused():
                return False
            self.window = self.user.GetForegroundWindow()
            self.held = 0x53
            self.deadline = time.monotonic()+3.0
            try:
                self.send(self.held)
                return True
            except OSError as exc:
                self.error = str(exc)
                self.release()
                return False

    def hold_test(self, direction, remaining):
        """Maintain direction-test steering while Qt renews short authorization.

        Parameters:
            direction: -1 for left or +1 for right during the steering phase.
            remaining: Remaining authorized hold time in seconds.

        Returns:
            True while the test key remains authorized; False when refused.

        Side effects:
            Refuses and releases when keys are missing, focus is lost, or time
            expires. Starts with a 100 ms pulse if needed, then renews a maximum
            150 ms authorization so the watchdog releases the key if the UI
            stops ticking.

        Raises:
            No exceptions escape; pulse() converts injection failures to False.
        """
        with self.lock:
            if not self.keys or not self.radar.game_focused() or remaining<=0:
                self.release()
                return False
            vk = self.keys[direction]
            if self.held != vk:
                self.release()
                if not self.pulse(direction,min(.1,remaining)):
                    return False
            self.deadline = time.monotonic()+min(.15,remaining)
            return True

    def release(self):
        """Release the currently held injected key, if any.

        Parameters:
            None.

        Returns:
            None.

        Side effects:
            Sends key-up for the held key and clears it on success. If Windows
            rejects the release, stores the error so the watchdog can retry.

        Raises:
            No exceptions escape; OSError is stored in ``error``.
        """
        with self.lock:
            if self.held is not None:
                try:
                    self.send(self.held, True)
                    self.held = None
                except OSError as exc:
                    self.error = str(exc)  # The watchdog will retry release.

    def watch_release(self):
        """Release held keys on timeout or focus loss, independent of Qt.

        Parameters:
            None.

        Returns:
            None.

        Side effects:
            Every 5 ms, releases a held injected key when its deadline expires
            or the foreground window differs from the one captured at press
            time. This is the safety backstop for stalled UI timers.

        Raises:
            No exceptions are raised directly.
        """
        while not self.done.wait(.005):
            with self.lock:
                if self.held is not None and (time.monotonic()>=self.deadline or self.user.GetForegroundWindow()!=self.window):
                    self.release()

    def close(self):
        """Shut down the input bridge and its background observation threads.

        Parameters:
            None.

        Returns:
            None.

        Side effects:
            Releases any held key, signals both daemon threads to stop, and
            briefly joins them so hooks are uninstalled promptly.

        Raises:
            No exceptions are raised directly.
        """
        self.release()
        self.done.set()
        if self.thread:
            self.thread.join(.2)
        if self.hook_thread:
            self.hook_thread.join(.2)
